version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: factory-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
